--------------------------------------------------------
--  파일이 생성됨 - 월요일-8월-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT
--------------------------------------------------------

  CREATE TABLE "DEVENUE"."PROJECT" 
   (	"PRO_ID" NUMBER, 
	"MEM_ID" NUMBER, 
	"PRO_NAME" VARCHAR2(100 BYTE), 
	"PRO_MAINTAIN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PRO_STA_ID" VARCHAR2(10 BYTE), 
	"PRO_RECRUIT" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"PRO_CREATE_DATE" DATE DEFAULT SYSDATE, 
	"PRO_PLAN" NUMBER, 
	"PRO_PLANDETAIL" NUMBER, 
	"PRO_SUMMARY" VARCHAR2(1000 BYTE), 
	"PRO_NEEDS" VARCHAR2(1000 BYTE), 
	"PRO_NEEDSDETAIL" VARCHAR2(1000 BYTE), 
	"PRO_RESOURCE" VARCHAR2(1000 BYTE), 
	"PRO_PAYMENT" NUMBER, 
	"PRO_START_DATE" DATE, 
	"PRO_DURATION" NUMBER, 
	"PRO_R_END_DATE" DATE, 
	"PRO_END_DATE" DATE, 
	"MC_ID" VARCHAR2(10 BYTE), 
	"DC_ID" VARCHAR2(10 BYTE), 
	"WT_ID" VARCHAR2(10 BYTE), 
	"PRO_RECRUIT_NUM" NUMBER, 
	"PRO_PLAN_PAPER" VARCHAR2(100 BYTE), 
	"PRO_PLAN_REPAPER" VARCHAR2(100 BYTE), 
	"PRO_LOCATION" VARCHAR2(20 BYTE), 
	"PRO_HELP" NUMBER, 
	"PRO_MANAGE" NUMBER, 
	"PRO_FUTUREPLAN" NUMBER, 
	"PRO_PRIORTY" NUMBER, 
	"PRO_CONTRACT" VARCHAR2(100 BYTE), 
	"MEM_TYPE_CODE" VARCHAR2(10 BYTE), 
	"PRO_WORKPLACE" VARCHAR2(100 BYTE), 
	"SIG_ID" NUMBER, 
	"PRO_PAY_STATUS" VARCHAR2(1 BYTE), 
	"PRO_PARENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_ID" IS '100~';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."MEM_ID" IS '시퀀스 100~';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_MAINTAIN" IS 'N / Y(신규/유지보수)';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_STA_ID" IS 'PS100~';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_RECRUIT" IS 'Y / N(모집중, 모집마감)';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_PLAN" IS '(1,2 ,3)아이디어만 있음, 필요한 내용 정리, 상세한 기획문서';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_PLANDETAIL" IS '체크박스(5개)->숫자';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_SUMMARY" IS '프로젝트 소개(100자 이내 요약)';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_NEEDS" IS '기능요약';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_NEEDSDETAIL" IS '구현하기 원하는 기능의 상세';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_PAYMENT" IS '예상금액->실제금액';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_R_END_DATE" IS '파트너스 모집마감일';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_END_DATE" IS '7일후 정산 기능 위해 필요';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."MC_ID" IS 'MC1~3';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."DC_ID" IS 'DC1~4';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."WT_ID" IS 'WT1~3';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_HELP" IS '1,2(인력있음, 인력없음)IT프로젝트경험있는인력유무';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_MANAGE" IS '1,2(경험있음, 경험없음)';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_FUTUREPLAN" IS '1, 2(계획있음, 계획없음)';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_PRIORTY" IS '1~4(빠름/완성도/금액/기간준수)';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_CONTRACT" IS '검수 끝나고 파트너 매칭후에 업데이트';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."MEM_TYPE_CODE" IS 'MT1~6';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_WORKPLACE" IS '근무지역인지 확인해야됨(민환)';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_PAY_STATUS" IS 'Y/N,Default:N';
   COMMENT ON COLUMN "DEVENUE"."PROJECT"."PRO_PARENT_ID" IS '연장신청 승인>>새프로젝트 생성 하므로 이전 프로젝트 ID';
--------------------------------------------------------
--  DDL for Table P_PROCESS
--------------------------------------------------------

  CREATE TABLE "DEVENUE"."P_PROCESS" 
   (	"PRO_PID" NUMBER, 
	"PRO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DEVENUE"."P_PROCESS"."PRO_ID" IS '시퀀스P1';
REM INSERTING into DEVENUE.PROJECT

Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (1,3,'마켓 글로벌 버전 다국어 지원 및 결제 추가 개발','N','PST3','Y',to_date('20/08/17','RR/MM/DD'),2,3,'iamwatermelon.com 이라는 국내 음원 플랫폼을 운영하고 있습니다. 현재 내부 개발자로 언어변환 정도의 작업은 가능하긴 하지만, 외주를 통해 다국어 버전 관련하여 결제모듈 및 다국어 버전 노하우를 깔끔하게 적용하고 싶어 이렇게 문의드립니다. 영어, 중국어로 구성할 계획입니다.','다국어 지원 ( 영어, 중국어 )','세부사항1111111','개발환경개발환경개발환경',3000000,to_date('20/08/31','RR/MM/DD'),20,to_date('20/08/31','RR/MM/DD'),null,'MC1','DC1','WT1',3,'기획보고서_제출.pdf','기획보고서_제출(수정).pdf','서울',1,1,1,2,null,'MT1',null,1,'N',1);
Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (2,3,'증권사 연계 RMS 구축','Y','PST3','Y',to_date('20/08/17','RR/MM/DD'),3,5,'증권사 연계 RMS 구축','다국어 지원 ( 영어, 중국어 )','기존 시스템에서 전문처리하는 부분에 대한 일부 개발을 요청드립니다.
','개발환경개발환경개발환경',5000000,to_date('20/08/31','RR/MM/DD'),15,to_date('20/08/31','RR/MM/DD'),null,'MC1','DC2','WT2',5,null,null,'서울',null,1,null,null,null,'MT1',null,1,'N',2);
Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (3,3,'종료','N','PST5','N',to_date('20/08/01','RR/MM/DD'),1,2,null,null,'세부사항세부사항세부사항세부사항','개발환경개발환경개발환경',7000000,to_date('20/08/03','RR/MM/DD'),7,to_date('20/08/01','RR/MM/DD'),to_date('20/08/10','RR/MM/DD'),'MC2','DC2','WT2',1,null,null,'부산',null,null,null,null,null,'MT2',null,1,'Y',3);
Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (6,3,'후보3','N','PST3','Y',to_date('20/08/11','RR/MM/DD'),2,2,'개요333333333333333333','이것을 개발해주시고 저것도 개발해주세요','세부사항세부사항세부사항세부사항','개발환경개발환경개발환경',3000000,to_date('20/08/28','RR/MM/DD'),30,to_date('20/08/26','RR/MM/DD'),null,'MC1','DC1','WT1',3,null,null,'서울',null,1,null,null,null,'MT1',null,1,'N',6);
Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (7,3,'후보4','N','PST3','Y',to_date('20/08/11','RR/MM/DD'),2,3,'개요44444444444444444','이것을 만들어주세요','세부사항세부사항세부사항세부사항','개발환경개발환경개발환경',4000000,to_date('20/08/29','RR/MM/DD'),40,to_date('20/08/27','RR/MM/DD'),null,'MC1','DC2','WT1',3,null,null,'서울',null,1,null,null,null,'MT1',null,1,'N',7);
Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (8,3,'후보5','N','PST3','Y',to_date('20/08/15','RR/MM/DD'),2,1,'개요55555555555555555','우리는 이것이 필요합니다','세부사항세부사항세부사항세부사항','개발환경개발환경개발환경',5000000,to_date('20/08/30','RR/MM/DD'),50,to_date('20/08/28','RR/MM/DD'),null,'MC1','DC1','WT1',3,null,null,'서울',null,1,null,null,null,'MT1',null,1,'N',8);
Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (4,3,'후보1','N','PST3','Y',to_date('20/08/01','RR/MM/DD'),2,3,'개요11111111111111111','나는 이것도 필요하고 저것도 필요해요','세부사항세부사항세부사항세부사항','개발환경개발환경개발환경',1000000,to_date('20/08/26','RR/MM/DD'),10,to_date('20/08/28','RR/MM/DD'),null,'MC1','DC1','WT1',3,null,null,'서울',null,1,null,null,null,'MT1',null,1,'N',4);
Insert into DEVENUE.PROJECT (PRO_ID,MEM_ID,PRO_NAME,PRO_MAINTAIN,PRO_STA_ID,PRO_RECRUIT,PRO_CREATE_DATE,PRO_PLAN,PRO_PLANDETAIL,PRO_SUMMARY,PRO_NEEDS,PRO_NEEDSDETAIL,PRO_RESOURCE,PRO_PAYMENT,PRO_START_DATE,PRO_DURATION,PRO_R_END_DATE,PRO_END_DATE,MC_ID,DC_ID,WT_ID,PRO_RECRUIT_NUM,PRO_PLAN_PAPER,PRO_PLAN_REPAPER,PRO_LOCATION,PRO_HELP,PRO_MANAGE,PRO_FUTUREPLAN,PRO_PRIORTY,PRO_CONTRACT,MEM_TYPE_CODE,PRO_WORKPLACE,SIG_ID,PRO_PAY_STATUS,PRO_PARENT_ID) values (5,3,'후보2','N','PST3','Y',to_date('20/08/02','RR/MM/DD'),2,4,'개요22222222222222222','클라이언트로서 정당한 요구를 하고자 한다','세부사항세부사항세부사항세부사항','개발환경개발환경개발환경',2000000,to_date('20/08/27','RR/MM/DD'),20,to_date('20/08/25','RR/MM/DD'),null,'MC1','DC1','WT1',3,null,null,'서울',null,1,null,null,null,'MT1',null,1,'N',5);

Insert into DEVENUE.P_PROCESS (PRO_PID,PRO_ID) values (1,3);
